### ISSUE TITLE
Collection.search is unable to find widgets when app = ['gfw'] 

### ISSUE THREAD

**Issue by edwardpmorris** [Vizzuality/LMIPy#59]
This call returns nothing, whereas using `app=['rw']` returns a list of widgets.
```
c = LMIPy.Collection(search='biomass', app=['gfw'], env='production', limit=1000, order='name', sort='desc', object_type=['widget'], server='https://api.resourcewatch.org', filters=None, mapbox_token=None)
c
```
A direct call to the API using curl seems to return correctly
`curl -X GET https://api.resourcewatch.org/v1/widget?app=gfw`

**Comment by 01painadam** [comment]
There are no Widgets stored with app=['gfw'] right now. Maybe make one as a test?
